name: CaseyConcepts
favicon: null
layout_spectrum: 0.360215
typography_spectrum: 0.6851851
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#010101'
    - '#70bd1f'
    - '#585858'
    - '#949494'
  brandStrength: 0.9401367725804448
  lightness: 0.9921575272455812
  saturation: 0.9466621759347618
  rhythmicContrast: 0.5084441094659269
purpose: []
