name: CaseyConcepts
favicon: null
layout_spectrum: 0.61946
typography_spectrum: 0.6851851
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74059684-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#010101'
    - '#70bd1f'
    - '#585858'
    - '#949494'
  brandStrength: 0.125
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
